name: buzz
description: An opinionated scalable framework for modern mobile apps
version: 0.1.0
homepage: https://github.com/luisburgos/buzz

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^2.0.0
  rxdart: ^0.27.4
  get: ^4.6.5
  neopop: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  coverage: ^1.0.2
  mockito: 5.3.0
