name: buzz
description: An opinionated scalable framework for modern mobile apps
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  event_bus: 2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
